### ISSUE TITLE
Duda Tarea 3

### ISSUE THREAD

**Issue by Tvergara** [IIC2213/Syllabus-2022-1#20]
Hola! Creo que puede haber un error en la ayuda del enunciado. Se dice que `1 <= t <= n`, sin embargo, esos no debieran ser suficientes configuraciones para mostrar una ejecución de una máquina lineal, ya que tiene `n` pasos en su ejecución (y por ende `n+1` configuraciones). Creo que debiera ser   `0 <= t <= n`, y además cambiar acorde la regla del estado inicial como `s(q_0, 0)` .

A modo de ejemplo, si la palabra w fuera `\epsilon`, con `1 <= t <= n` no tiene consistencia, ya que quedaría  `1 <= t <= 0`, y por ende no habría ninguna configuración (ni siquiera la inicial).

**Comment by juanreutter** [comment]
(igual explicité el tema de los largos en el enunciado actual)

**Comment by Tvergara** [comment]
Genial, gracias!
