### ISSUE TITLE
Duda Tarea 1

### ISSUE THREAD

**Issue by Tvergara** [IIC2213/Syllabus-2022-1#3]
Hola, no hay problema con usar algún caracter fuera del alfabeto {0,1,#} durante la ejecución de la máquina?
Me refiero por ejemplo a:
```
q0,1
q1,+,>
```

**Comment by juanreutter** [comment]
Hola, si hay problemas: La máquina tiene que usar solo los caracteres del alfabeto (y el blanco). Una máquina que usa mas caracteres corre sobre un alfabeto distinto, y por lo tanto no cumple con lo pedido.

**Comment by Arcoirisky** [comment]
Pregunta, no pasa nada con escribir blanco ¿no? 

q0,1
q1,_,>

**Comment by juanreutter** [comment]
Blanco está bien! la máquina escribe blanco y cualquier caracter del alfabeto.
