### ISSUE TITLE
[Tarea 6] Enunciado: pregunta 1

### ISSUE THREAD

**Issue by jtcaraball** [IIC2213/Syllabus-2022-1#43]
Hola! El enunciado de la pregunta 1 pide demostrar qué '$G$ es lógicamente a $N$', con esto quiere decir lógicamente equivalente? Y de ser ese el caso, como nos aproximamos si creemos que no lo son? (Aun no le doy todas las vueltas que amerita pero estoy casi seguro de haber encontrado una oración que es satisfacible por $N$ pero no por $G$).

Saludos!

**Comment by juanreutter** [comment]
si! Logicamente equivalente. Voy a subir una correccion.
Ojo que en la tarea no se entrega una estructura G en particular, solo se pide demostrar que existe una estructura que satisface esas condiciones. Luego, si no crees que eso es verdad, tendrias que demostrar en tu tarea que todas las estructuras cuyo dominio contiene a los naturales y que tienen un elemento que es mayor a los naturales son necesariamente no-equivalentes a N.
