### ISSUE TITLE
[Tarea 6] Buzón

### ISSUE THREAD

**Issue by sofiaemd** [IIC2213/Syllabus-2022-1#48]
Hola!
¿Podrían por favor abrir el buzón de entrega para la tarea 6?
Muchas gracias!

**Comment by juanreutter** [comment]
listo

**Comment by sofiaemd** [comment]
Podrían agregarle intentos ilimitados por favor?

**Comment by juanreutter** [comment]
Perdon :S Ahora si esta

**Comment by sofiaemd** [comment]
Muchas gracias!!
