### ISSUE TITLE
Recorreccion T1

### ISSUE THREAD

**Issue by oscars810** [IIC2213/Syllabus-2022-1#9]
Hola!

Quería saber si se habilitará algun form para recorregir la Tarea 1 o hay que mandar mail al profesor/ayudantes.

**Comment by Drpinto1** [comment]
¡Hola!

Se acaba de mandar un anuncio sobre eso, avisaremos cuando estén listas todas las notas y junto con eso el funcionamiento de la recorrección.

¡Saludos!
